template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "cent2136"
__REPO__ = "lang-oji"
__UND2C__ = "oj"
__UNDEFINED__ = "Ojibwa"
__UND__ = "oji"
