template = "https://github.com/giellalt/template-lang-und"
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "cent2136"
__REPO__ = "lang-oji"
__UND2C__ = "oj"
__UNDEFINED__ = "Ojibwa"
__UND__ = "oji"
